<?php
namespace Xin\Thrift\Notice;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface NoticeIf {
  /**
   * @param \Xin\Thrift\Notice\Email[] $emails
   * @param \Xin\Thrift\Notice\EmailContent $content
   * @return bool
   * @throws \Xin\Thrift\Notice\ThriftException
   */
  public function sendEmail(array $emails, \Xin\Thrift\Notice\EmailContent $content);
  /**
   * @param \Xin\Thrift\Notice\EmailSearch $input
   * @return \Xin\Thrift\Notice\EmailInfo[]
   * @throws \Xin\Thrift\Notice\ThriftException
   */
  public function getEmailList(\Xin\Thrift\Notice\EmailSearch $input);
}


